M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu24.04.1} date 2024-11-07T17:00:29-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-07T17:00:29-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1220
%
G90
G05
T1
X0.1028Y-0.6415
X0.3303Y-0.6415
T2
X0.748Y-0.5531
T3
X0.1506Y-0.0738
X0.2687Y-0.0738
T4
X0.0886Y-0.2736
M30
