M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu22.04.1} date 2024-08-29T21:18:50-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-29T21:18:50-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1220
%
G90
G05
T1
X4.0512Y-3.9331
X4.5315Y-3.9331
M30
