M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu24.04.1} date 2024-11-07T20:05:32-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-07T20:05:32-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1220
%
G90
G05
T1
X0.0886Y-0.4154
X0.5689Y-0.4154
M30
