M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu22.04.1} date 2024-10-23T16:58:35-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-23T16:58:35-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1220
%
G90
G05
T1
X4.0654Y-4.1593
X4.2929Y-4.1593
T2
X4.7992Y-4.0807
T3
X4.1132Y-3.5915
X4.2313Y-3.5915
T4
X4.0512Y-3.7913
M30
